logging:
  file:
    name: log.blog-pro.log
  level:
    com:
      example:
        blog2: info
    root: warn
server:
  compression:
    enabled: true
    mime-types: application/javascript,text/css,application/json,application/xml,text/html,text/xml,text/plain
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: 123456
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf-8
    username: root
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
