logging:
  file:
    name: logs/
  level:
    com:
      example:
        blog2: info
    root: info
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
  mapper-locations: classpath:/mapper/**/*.xml

server:
  compression:
    enabled: true
    mime-types: application/javascript,text/css,application/json,application/xml,text/html,text/xml,text/plain
  port: 8090

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 123456
#    url: jdbc:mysql://192.168.88.130:3306/blog?useUnicode=true&characterEncoding=utf-8
    url: jdbc:mysql://127.0.0.1:3306/blog?useUnicode=true&characterEncoding=utf-8
    username: root
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5                                       # 初始化大小
      min-idle: 5                                           # 最小连接数
      max-active: 15                                        # 最大连接数
      max-wait: 5000                                        # 获取连接时的最大等待时间
      min-evictable-idle-time-millis: 300000                # 一个连接在池中最小生存的时间，单位是毫秒
      time-between-eviction-runs-millis: 90000              # 多久才进行一次检测需要关闭的空闲连接，单位是毫秒

three:
  oss:
    accessKey: Djaw32O83II324ZtpxvlCmUH1FTi7hOuOVr6vRuN
    blog: text/blog/
    bucket: mxp-blog
    essay: text/essay/
    region: http://roxuynt15.hd-bkt.clouddn.com
    secretKey: 6nX92UklXiZf7KOYBtTVOss3xG4RGvP4O1mYmi3s
  location:
    key: FJNBZ-4B6KX-UJM4X-ZWZUG-DPMMS-GQFXD

rsa:
  publicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAg703+zHtuIrTWC5FJB0Msif7npCvIPXM+6rcFVEUZSSvR1BOu+YSEDAg7UqqG8lIujkhqBwksI+F4P9lRufM/TohMqKwBPAZia+Th1soltySb0nGWMqHrVYH48jloz5E5j62ZxwaWWYgg1AFCzIuO0/qUw1SPj5V0ltI86sNt+14EU+knhNL3kjpPlUaxDY/H3Ea8YIy6aZ3gI4SOZRq6+AS9iaRAaX6bXGbt9Vs54sPBartpULqCr3IZFozVnQVNCy7Ye0gSePebE8j91giHZNNnehnpkn45H8CzxwCpkMVL0xxZaCR9fVlTEinWHjhYyeDDVlpYjqkSS9u5QEYVwIDAQAB
  privateKey: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCDvTf7Me24itNYLkUkHQyyJ/uekK8g9cz7qtwVURRlJK9HUE675hIQMCDtSqobyUi6OSGoHCSwj4Xg/2VG58z9OiEyorAE8BmJr5OHWyiW3JJvScZYyoetVgfjyOWjPkTmPrZnHBpZZiCDUAULMi47T+pTDVI+PlXSW0jzqw237XgRT6SeE0veSOk+VRrENj8fcRrxgjLppneAjhI5lGrr4BL2JpEBpfptcZu31Wzniw8Fqu2lQuoKvchkWjNWdBU0LLth7SBJ495sTyP3WCIdk02d6GemSfjkfwLPHAKmQxUvTHFloJH19WVMSKdYeOFjJ4MNWWliOqRJL27lARhXAgMBAAECggEAZocUE4aXKYG53C4el22YXOsrNAwMkE1cnB0srdZtVg5H7+t7a1cyhbC/X441d+yekng2TnygvVzl5+c8rgNnkUj1X1AoR5+JcJPZ8IUswMSnnr8/BAmTsH59I3VN609iFgOGuBayFxOZiDj1w/Ho8zZN+xcqA9FFv7JVw3ZD9flXGSrtnZWhsiiIjP6GajhFJP/3nOBaDCbq/w6i7TKkgM+ZmxqA2rtfWPz46Xi1nVmSuutyCIBvg6DGOJAsupatj0lF5AjA2CMxY2ERDHtVqFwrA5wg/NgH/48LpU+AZds4NTCsg2yKEZSyBBbrSYXpdhZ82Owifd1MRqUi+XXIGQKBgQDHncEV//WMxxrcXspG4PtvekR/L+uzykVfAQYjDQ/H6CR3bPqoM2WyOXHV9hwuyeaGLvIxCns7T8cPfg9GbLE3bFE90Tmprlvmn94/qArshCn3pq7/Jm0n8Wt7roxd56X3UVDtEODT/xi4QNw/ia4lEvXK7/5pb4Z15NiiFKFfPQKBgQCo80XtM0cuz+WyOGZ8u2EpDKNDI7Tth9J96NbCcws7G0gyJ+z0cFUPj4LTvibigbAT/cOy33Bs1YNwXyVe9rQVlBDjUj1rWaew75PZC0uxYdnJhuaW/JUdKW2VtgEpjwJkXltkwBKOE4mTlCZGyjGEYp/qCapilCZXHgoMtZaPIwKBgEPTOlQ7UDexP1M5cgl7UHOkW7nLko7YX5HUSz2FpqMKIbnicZjNPfS8yA0nPpQ3Tfix4uD+6rhQdxawgogvTlfCmigi+zDIabmHAIEom+2ZSpk3LabMa7JyuU6hFFij6SSLoK+sWHgv6TpR74Q3R9CZDKMTwKIantlYFLOdxucRAoGBAJkrtQHPs4FlSkHBkGkVGIk2w+1iue1/bf5o0guIcW4s1c9jExipnvR0j4+YnXhNS21Ua9AHcs245WlDWYY29B18F7OAI97ncXigO9JSw1UV+XUTsIrChA3kOU25rGQZG3oTcZht6mSUoe4CKpGTTkFPiNuN18N3vSrOOR48ozsxAoGAc217lVSuHJe0X6NwOhAQLKY2APTCIwChiMLo1uEEEIs9Eatb2eopFH8cDcRfPXWPYK5SCxGDgF0rkzZ375a7oESG1j9qhZutNCj4IT5ANl5rWtiC8j8WqaJntyMXpWj0yUAQH2FckRWZplXQBFQY11nArQzx/xxxNJM7I/MsM54=


my:
  thread:
    core: 12
    max: 12
