logging:
  file:
    name: logs/
  level:
    com:
      example:
        blog2: info
    root: warn
server:
  compression:
    enabled: true
    mime-types: application/javascript,text/css,application/json,application/xml,text/html,text/xml,text/plain
  port: 8090

mybatis-plus:
  global-config:
    db-config:
      id-type: auto
  mapper-locations: classpath:/mapper/**/*.xml


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 123456
    url: jdbc:mysql://192.168.88.130:3306/blog?useUnicode=true&characterEncoding=utf-8
    #    url: jdbc:mysql://127.0.0.1:3306/blog?useUnicode=true&characterEncoding=utf-8
    username: root
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5                                       # 初始化大小
      min-idle: 5                                           # 最小连接数
      max-active: 30                                        # 最大连接数
      max-wait: 6000                                        # 获取连接时的最大等待时间
      min-evictable-idle-time-millis: 300000                # 一个连接在池中最小生存的时间，单位是毫秒
      time-between-eviction-runs-millis: 60000              # 多久才进行一次检测需要关闭的空闲连接，单位是毫秒
  #      filters: stat                                         # 配置扩展插件：stat-监控统计，log4j-日志，wall-防火墙（防止SQL注入），去掉后，监控界面的sql无法统计   ,wall
  #      validation-query: SELECT 1                            # 检测连接是否有效的 SQL语句，为空时以下三个配置均无效
  #      test-on-borrow: true                                  # 申请连接时执行validationQuery检测连接是否有效，默认true，开启后会降低性能
  #      test-on-return: true                                  # 归还连接时执行validationQuery检测连接是否有效，默认false，开启后会降低性能
  #      test-while-idle: true                                 # 申请连接时如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效，默认false，建议开启，不影响性能
  #      stat-view-servlet:
  #        enabled: true                                       # 是否开启 StatViewServlet
  #        allow: 127.0.0.1                                    # 访问监控页面 白名单，默认127.0.0.1
  #        deny: 192.168.56.1                                  # 访问监控页面 黑名单
  #        login-username: admin                               # 访问监控页面 登陆账号
  #        login-password: admin                               # 访问监控页面 登陆密码
#        filter:
#          stat:
#            log-slow-sql: true                                # 是否开启 慢SQL 记录，默认false
  #            enabled: true                                     # 是否开启 FilterStat，默认true
#            slow-sql-millis: 1000                              # 慢 SQL 的标准，默认 3000，单位：毫秒
  #          merge-sql: false                                  # 合并多个连接池的监控数据，默认false

three:
  oss:
    accessKey: Djaw32O83II324ZtpxvlCmUH1FTi7hOuOVr6vRuN
    blog: text/blog/
    bucket: mxp-blog
    essay: text/essay/
    region: http://roxuynt15.hd-bkt.clouddn.com
    secretKey: 6nX92UklXiZf7KOYBtTVOss3xG4RGvP4O1mYmi3s
  location:
    key: FJNBZ-4B6KX-UJM4X-ZWZUG-DPMMS-GQFXD

rsa:
  publicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAogfO/bveLnn0Tb7dnxIVXj25KjTmVFBllP0zqYY3FwNVKQ03iKI7kYd01sbnlRHLVcu74nmk41Ux7mHPQx5nghyktLiyovsbwBkqpWNnfmT9DNq89R6Lw9Mrw/L0pJDc9ACGkksGDyFvQjEt/3+h/phMjEkgHU2kA+F0ZCCgZgVOsKQXwL452+NpLH4rekwfXRJw0GCaZeyMPkNYbItsHvCD1CCPYeCJQw9sfYX/TKeDO2LGZKH5xCi672SqAeu36fpUsw4LXAosTln9Xwpvd2+JT3+GOzKhv05j45YtY96L4/zho0FGn7YSPAd+o3JGMg6B0Cb1unnp6PMKwEBMewIDAQAB
  privateKey: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCiB879u94uefRNvt2fEhVePbkqNOZUUGWU/TOphjcXA1UpDTeIojuRh3TWxueVEctVy7vieaTjVTHuYc9DHmeCHKS0uLKi+xvAGSqlY2d+ZP0M2rz1HovD0yvD8vSkkNz0AIaSSwYPIW9CMS3/f6H+mEyMSSAdTaQD4XRkIKBmBU6wpBfAvjnb42ksfit6TB9dEnDQYJpl7Iw+Q1hsi2we8IPUII9h4IlDD2x9hf9Mp4M7YsZkofnEKLrvZKoB67fp+lSzDgtcCixOWf1fCm93b4lPf4Y7MqG/TmPjli1j3ovj/OGjQUafthI8B36jckYyDoHQJvW6eeno8wrAQEx7AgMBAAECggEAZYobL2tCK0IF1Yrc+8irV2m61jZceU4AusOKUpxnfaZ7AcTknl18kxCeKdJwYjzKfjO0xJKSwFwtdEQbTOaK20Dz/sUYPYa7t0CONyL6Qn0rD5ksfTftQoTdkmh444Bc1xRVQOx/GZBMVuDXAJyNei0bG3bgBz0Woc/xzqWbnxKDaqpS4d+LmdjSss4Q3HQ6L2uh0b3RaUyQ5HPSGTzoo8eA3iRAvxYW7dtgf2LoDztZ2Uv9HCL8v0/MnvVnRbOPPI5BwEr2dItGL5uj2BTrjvpCcd352WUlu4mMjdADywGDgyAn4GaPI9+G6rdplwVyO5nmVoMPjtd50Ul2mVm+AQKBgQD7hkcWd5thFlFYi0gUpUIs3hheaqKTm+mK4+RQxlGTg695fFs93L6Way98x9UiG86Oa2pCaMo0TZTdsSVqV8x/dCob+ElBcr5hM6zJhE3iuCH9mEw2DxDAFmyut5OqO/M3f4f1EWMuntgNQ7pI73A4UdPEvbhq4Kxb7RSn+QdmgQKBgQCk6eAn1+makU7quKsjscOoMp7b7DIrfv0FKVLPK1y0CbGvELExItqT4tfn3RBZO1kUmRTpaRx+ZvQhkULv9Y07U6iDiaicFmOf87t0iFDKm1aQCmyfoB1ZXxWXwUFlWsZGo0pB5lAj7mAQswxLcSsmBFtJ/bD2rKFbUK7TqFDM+wKBgQCYNwncSePpXGU8LYYgoGYs2vdqZCQhKlCqcgHg9DO4DxBpd92L0YQxaYpifFi6fJODUvQKXnpILs8xXpwjACFM3JMDPD2w8uzNzET76yprUz2Wx80PRgzAApIhJg2iDwfAhVhU8gHQ2+YqGNuqeeSy4KpEvP/XBkKomxBOGwHkgQKBgCpVv616yAVd+BxZe9WV9Nxg4lcis15nIx0IFrIIN6wgMPT4HAS5JdOBEFv9bAz8J0oaYjvpN99bHqDfYYeoSbFJMKFT3Wz0cm7FawHnXJYmenpPssLnn6Epv6lNezRBsVTA5nc0YK5Yq2CeFjHnw2PnCmhcL+mjN2jxtW+wbc2xAoGBAMBpqCHH3nyH+ckyPIao/gKkA/PFb4ur2e9JfhjEfpne80zwD5p6Md1Hm01j7vMu/uM+LhOq/J6w76eb1DRu4nzCngTS23/RErXZwvMCqkMe/GqM3gEvmqJqDX10r3RY86NM9tNSiX5ntgW+pyBLOxMJHwGG2+5xJ8nu7uGnl5K6

my:
  thread:
    core: 12
    max: 12
